name: Run Tests and Publish Allure Report

on:
  push:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests and generate Allure results
        run: mvn clean test "-DsuiteXmlFile=testng.xml"

      - name: Generate Allure report
        run: |
          mkdir -p allure-report
          npx allure generate target/allure-results --clean -o allure-report

      - name: Upload Allure Report as GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: allure-report

  deploy:
    needs: test-and-report
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
