name: Run Tests and Publish Allure Report

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test "-DsuiteXmlFile=testng.xml"

      - name: Install Allure Commandline
        uses: allegro-actions/setup-allurectl@v1

      - name: Generate Allure report
        run: |
          allurectl generate \
            --results target/allure-results \
            --output allure-report

      - name: Upload HTML to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
